version: '3.7'

services:
  db:
    image: "postgres"

    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
       - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./data/iris.csv:/data/iris.csv
       - pg_api:/var/lib/postgresql/data
    ports:
       - 5432:5432
  web:
    build: ./api
    env_file:
       - ".env"
    ports:
       - 8080:8080
    depends_on:
      - "db"  
  dash_board_perron:
    build: ./shiny
    env_file:
      - ".env"   
    ports:
      - 4999:4999 #compu-contenedor
    depends_on:
      - "web"  
volumes:
  pg_api: